# Generated by Django 2.1.3 on 2019-01-13 07:24

from django.db import migrations, models
import ecomapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0011_auto_20190109_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction_title', models.CharField(max_length=30)),
                ('instruction_pdf', models.FileField(upload_to=ecomapp.models.image_folder)),
            ],
        ),
    ]
