# Generated by Django 2.1.3 on 2019-01-13 12:20

from django.db import migrations, models
import ecomapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0012_instruction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Instruction',
        ),
        migrations.AddField(
            model_name='product',
            name='instruction_pdf',
            field=models.FileField(default=1, upload_to=ecomapp.models.image_folder),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='instruction_title',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
