# Generated by Django 2.1.1 on 2019-02-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0016_auto_20190122_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150, verbose_name='Имя пользователя')),
                ('sender', models.EmailField(max_length=254, verbose_name='E-mail - пользователя')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('copy', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Контактная форма',
                'verbose_name_plural': 'Форма обратной связи',
                'db_table': 'contact_form',
            },
        ),
    ]
