# Generated by Django 2.2.6 on 2019-10-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0017_mailbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbox',
            name='message',
            field=models.TextField(max_length=150, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='mailbox',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='mailbox',
            name='subject',
            field=models.CharField(max_length=20, verbose_name='Имя пользователя'),
        ),
    ]
